name: onednn-doc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - doxyrest=2.1.2
  - doxygen=1.8.14
  - graphviz=2.40.1
  - sphinx=6.2.1
  - sphinx-book-theme=1.1.4
  - sphinx-copybutton=0.5.2
